export const MOCK_WARNINGS = [
  {
    id:          'w-1',
    type:        'wind',
    severity:    'ORANGE',
    region:      'Brittany, France',
    country:     'FR',
    provider:    'Météo-France',
    start:       '2026-03-18T14:00:00Z',
    end:         '2026-03-19T02:00:00Z',
    description: 'Severe gale force winds expected along the coast. Gusts up to 110km/h. Secure outdoor objects.',
    lat:         48.2020,
    lng:         -2.9326,
    radius:      1.5,
  },
  {
    id:          'w-2',
    type:        'flood',
    severity:    'RED',
    region:      'North Rhine-Westphalia, Germany',
    country:     'DE',
    provider:    'Deutscher Wetterdienst (DWD)',
    start:       '2026-03-18T08:00:00Z',
    end:         '2026-03-20T12:00:00Z',
    description: 'Extreme rainfall leading to rapid rise in river levels. Immediate risk of flooding in urban areas.',
    lat:         51.4332,
    lng:         7.6615,
    radius:      2.0,
  },
  {
    id:          'w-3',
    type:        'heat',
    severity:    'YELLOW',
    region:      'Andalusia, Spain',
    country:     'ES',
    provider:    'AEMET',
    start:       '2026-03-18T12:00:00Z',
    end:         '2026-03-18T20:00:00Z',
    description: 'Temperatures reaching 38°C. Stay hydrated and avoid outdoor activities during peak hours.',
    lat:         37.3891,
    lng:         -5.9845,
    radius:      3.0,
  },
  {
    id:          'w-4',
    type:        'fire',
    severity:    'ORANGE',
    region:      'Peloponnese, Greece',
    country:     'GR',
    provider:    'HNMS',
    start:       '2026-03-18T10:00:00Z',
    end:         '2026-03-21T18:00:00Z',
    description: 'High risk of forest fires due to dry conditions and local winds. Strict ban on open fires.',
    lat:         37.5615,
    lng:         22.3482,
    radius:      2.5,
  },
  {
    id:          'w-5',
    type:        'storm',
    severity:    'YELLOW',
    region:      'Lombardy, Italy',
    country:     'IT',
    provider:    'MeteoAM',
    start:       '2026-03-18T16:00:00Z',
    end:         '2026-03-18T23:00:00Z',
    description: 'Isolated heavy thunderstorms with localized hail and lightning risk.',
    lat:         45.4642,
    lng:         9.1900,
    radius:      1.8,
  },
];
